### PR TITLE
46 Test cases fixed

### PR DESCRIPTION
**Pull request by rangapuram**

### CODE REVIEW

**Comment by pgambling** [comment]
We don't want to store answers in the repository itself.

**Comment by zaksaid** [comment]
@rangapuram We're you trying to complete the assessment? If so please fork the repo. Thanks.

**Comment by rangapuram** [comment]
@zaksaid Quickly wanted to see code .. so did a PR.... Sure. I will try to complete when i get time. In particular  for RegEx !!!!.

**Comment by zaksaid** [comment]
@rangapuram Not sure what you mean by "wanted to see the code". Were you looking to create a diff between your branch and upstream?

**Pull request closed without merging**
